import Head from 'next/head'
import { auth } from '../firebase'
import { signOut } from "firebase/auth";
import { useAuthState } from 'react-firebase-hooks/auth';
import styles from '../styles/Home.module.css'

export default function Home() {

  const [user] = useAuthState(auth)

  const logOff = () => {
    signOut(auth).then(() => {
      // Sign-out successful.
    }).catch((error) => {
      // An error happened.
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Nextjs Firebase Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome {user.displayName}</h1>

      <button onClick={logOff}>Sign out</button>

    </div>
  )
}
